### ISSUE TITLE
Quaternion.toString() and toStringAsYawPitchRoll() are moved to QuaternionReadOnly

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/euclid-core#7]
maybe also getX, Y, Z, and S

**Comment by SylvainBertrand** [comment]
- toString() cannot be added to QuaternionReadOnly (can't add toString() to an interface), but it is actually available without explicitly adding it.
- toStringAsYawPitchRoll() is moved up to the read-only interface, I also added it for axis-angle and rotation matrix.
- QuaternionReadOnly already has the getters for the individual components through Tuple4DReadOnly.
